# Generated by Django 4.2.3 on 2023-07-09 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='identifier',
        ),
        migrations.AddField(
            model_name='image',
            name='disease',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='diseases.disease'),
            preserve_default=False,
        ),
    ]
