# Generated by Django 4.2.3 on 2023-07-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_remove_image_identifier_image_disease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='identifier',
            field=models.CharField(max_length=100),
        ),
    ]
