# Generated by Django 4.2.3 on 2023-07-11 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0003_alter_disease_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='death_rate',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='number_affected_in_herd',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='disease',
            name='other_livestock_affected',
            field=models.TextField(),
        ),
    ]
